let heroesQuantity = 124; //Общее количество героев

let heroInfo = {
   //Объект с информацией о герое
   name: [
      "NotAHero",
      "Abaddon",
      "Underlord",
      "Alchemist",
      "Ancient Apparition",
      "Antimage",
      "Arc Warden",
      "Axe",
      "Bane",
      "Batrider",
      "Beastmaster",
      "Bloodseeker",
      "Bounty Hunter",
      "Brewmaster",
      "Bristleback",
      "Broodmother",
      "Centaur Warrunner",
      "Chaos Knight",
      "Chen",
      "Clinkz",
      "Crystal Maiden",
      "Dark Seer",
      "Dark Willow",
      "Dawnbreaker",
      "Dazzle",
      "Death Prophet",
      "Disruptor",
      "Doom",
      "Dragon Knight",
      "Drow Danger",
      "Earth Spirit",
      "Earthshaker",
      "Elder Titan",
      "Ember Spirit",
      "Enchantress",
      "Enigma",
      "Faceless Void",
      "Nature's Prophet",
      "Grimstroke",
      "Gyroco",
      "Hoodwink",
      "Huskar",
      "Invoker",
      "Jakiro",
      "Juggernaut",
      "Keeper of the light",
      "Kunkka",
      "Legion Commander",
      "Leshrac",
      "Lich",
      "Lifestealer",
      "Lina",
      "Lion",
      "Lone Druid",
      "Luna",
      "Lycan",
      "Magnataur",
      "Marci",
      "Mars",
      "Medusa.",
      "Meepo",
      "Mirana",
      "Monkey King",
      "Morphling",
      "Muerta",
      "Naga_siren",
      "Necrolyte",
      "Shadow Fiend",
      "Night Stalker",
      "Nyx",
      "Outworld Destroyer",
      "Ogre Magi",
      "Omniknight",
      "Oracle",
      "Pangolier",
      "Phantom Assassin",
      "Phantom Lancer",
      "Phoenix",
      "Primal Beast",
      "Puck",
      "Pudge",
      "Pugna",
      "Queen of pain",
      "Clockwerk",
      "Razor",
      "Riki",
      "Rubick",
      "Sand King",
      "Shadow Demon",
      "Shadow Shaman",
      "Shredder",
      "Silencer",
      "Wraith king",
      "Skywrath Mage",
      "Slardar",
      "Slark",
      "Snapfire",
      "Sniper",
      "Spectre",
      "Spirit Breaker",
      "Storm Spirit",
      "Sven",
      "Techies",
      "Templar Assassin",
      "Terrorblade",
      "Tidehunter",
      "Tinker",
      "Tiny",
      "Treant Protector",
      "Troll Warlord",
      "Tusk",
      "Undying",
      "Ursa",
      "Vengeful Spirit",
      "Venomancer",
      "Viper",
      "Visage",
      "Void Spirit",
      "Warlock",
      "Weaver",
      "Windranger",
      "Winter Wyvern",
      "IO",
      "Witch_doctor",
      "Zeus",
   ],
   image: [
      "NotAHero",
      "./images/heroes/abaddon.png",
      "./images/heroes/abyssal_underlord.png",
      "./images/heroes/alchemist.png",
      "./images/heroes/ancient_apparition.png",
      "./images/heroes/antimage.png",
      "./images/heroes/arc_warden.png",
      "./images/heroes/axe.png",
      "./images/heroes/bane.png",
      "./images/heroes/batrider.png",
      "./images/heroes/beastmaster.png",
      "./images/heroes/bloodseeker.png",
      "./images/heroes/bounty_hunter.png",
      "./images/heroes/brewmaster.png",
      "./images/heroes/bristleback.png",
      "./images/heroes/broodmother.png",
      "./images/heroes/centaur.png",
      "./images/heroes/chaos_knight.png",
      "./images/heroes/chen.png",
      "./images/heroes/clinkz.png",
      "./images/heroes/crystal_maiden.png",
      "./images/heroes/dark_seer.png",
      "./images/heroes/dark_willow.png",
      "./images/heroes/dawnbreaker.png",
      "./images/heroes/dazzle.png",
      "./images/heroes/death_prophet.png",
      "./images/heroes/disruptor.png",
      "./images/heroes/doom_bringer.png",
      "./images/heroes/dragon_knight.png",
      "./images/heroes/drow_ranger.png",
      "./images/heroes/earth_spirit.png",
      "./images/heroes/earthshaker.png",
      "./images/heroes/elder_titan.png",
      "./images/heroes/ember_spirit.png",
      "./images/heroes/enchantress.png",
      "./images/heroes/enigma.png",
      "./images/heroes/faceless_void.png",
      "./images/heroes/furion.png",
      "./images/heroes/grimstroke.png",
      "./images/heroes/gyrocopter.png",
      "./images/heroes/hoodwink.png",
      "./images/heroes/huskar.png",
      "./images/heroes/invoker.png",
      "./images/heroes/jakiro.png",
      "./images/heroes/juggernaut.png",
      "./images/heroes/keeper_of_the_light.png",
      "./images/heroes/kunkka.png",
      "./images/heroes/legion_commander.png",
      "./images/heroes/leshrac.png",
      "./images/heroes/lich.png",
      "./images/heroes/life_stealer.png",
      "./images/heroes/lina.png",
      "./images/heroes/lion.png",
      "./images/heroes/lone_druid.png",
      "./images/heroes/luna.png",
      "./images/heroes/lycan.png",
      "./images/heroes/magnataur.png",
      "./images/heroes/marci.png",
      "./images/heroes/mars.png",
      "./images/heroes/medusa.png",
      "./images/heroes/meepo.png",
      "./images/heroes/mirana.png",
      "./images/heroes/monkey_king.png",
      "./images/heroes/morphling.png",
      "./images/heroes/muerta.png",
      "./images/heroes/naga_siren.png",
      "./images/heroes/necrolyte.png",
      "./images/heroes/nevermore.png",
      "./images/heroes/night_stalker.png",
      "./images/heroes/nyx_assassin.png",
      "./images/heroes/obsidian_destroyer.png",
      "./images/heroes/ogre_magi.png",
      "./images/heroes/omniknight.png",
      "./images/heroes/oracle.png",
      "./images/heroes/pangolier.png",
      "./images/heroes/phantom_assassin.png",
      "./images/heroes/phantom_lancer.png",
      "./images/heroes/phoenix.png",
      "./images/heroes/primal_beast.png",
      "./images/heroes/puck.png",
      "./images/heroes/pudge.png",
      "./images/heroes/pugna.png",
      "./images/heroes/queenofpain.png",
      "./images/heroes/rattletrap.png",
      "./images/heroes/razor.png",
      "./images/heroes/riki.png",
      "./images/heroes/rubick.png",
      "./images/heroes/sand_king.png",
      "./images/heroes/shadow_demon.png",
      "./images/heroes/shadow_shaman.png",
      "./images/heroes/shredder.png",
      "./images/heroes/silencer.png",
      "./images/heroes/skeleton_king.png",
      "./images/heroes/skywrath_mage.png",
      "./images/heroes/slardar.png",
      "./images/heroes/slark.png",
      "./images/heroes/snapfire.png",
      "./images/heroes/sniper.png",
      "./images/heroes/spectre.png",
      "./images/heroes/spirit_breaker.png",
      "./images/heroes/storm_spirit.png",
      "./images/heroes/sven.png",
      "./images/heroes/techies.png",
      "./images/heroes/templar_assassin.png",
      "./images/heroes/terrorblade.png",
      "./images/heroes/tidehunter.png",
      "./images/heroes/tinker.png",
      "./images/heroes/tiny.png",
      "./images/heroes/treant.png",
      "./images/heroes/troll_warlord.png",
      "./images/heroes/tusk.png",
      "./images/heroes/undying.png",
      "./images/heroes/ursa.png",
      "./images/heroes/vengefulspirit.png",
      "./images/heroes/venomancer.png",
      "./images/heroes/viper.png",
      "./images/heroes/visage.png",
      "./images/heroes/void_spirit.png",
      "./images/heroes/warlock.png",
      "./images/heroes/weaver.png",
      "./images/heroes/windrunner.png",
      "./images/heroes/winter_wyvern.png",
      "./images/heroes/wisp.png",
      "./images/heroes/witch_doctor.png",
      "./images/heroes/zuus.png",
   ],
   id: [
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
      21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
      39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
      57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
      75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
      93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
      109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
      124, 125,
   ],
};

let randId = 0;
let back = 0;
let heroButton = document.querySelector(".choose-button");
let heroImage = document.querySelector(".hero-image");
let lastHeroId = document.querySelector(".last-hero__id");
let lastHeroName = document.querySelector(".last-hero__name");

heroButton.addEventListener("click", heroesRandom);

function heroesRandom() {
   randId = Math.ceil(Math.random() * heroesQuantity);
   back = back + 1;
   if (randId !== 0) {
      heroButton.textContent = "Еще раз";
   }
   if (back === 25) {
      alert("Поздравляем, вы нажали на кнопку целых 25 раз 🎉");
   }
   if (back === 50) {
      alert(
         "Поздравляем, вы нажали уже аж 50 раз. Это большое достижение. Но дальше продолжать не советую. Дальше ачивок не будет"
      );
   }
   heroImage.setAttribute(
      `style`,
      `background-image: url('${heroInfo.image[randId]}')`
   );
   lastHeroId.textContent = heroInfo.id[randId];
   lastHeroName.textContent = `- ${heroInfo.name[randId]}`;
   console.log(
      "Ваш герой:    --- " +
         heroInfo.name[randId] +
         " ---     под номером  - " +
         randId +
         " -"
   );
   console.log(back);
}

console.log(heroInfo.id[0]);
