let heroInfo = {
   //Объект с информацией о герое
   name: [
      "Abaddon",
      "Underlord",
      "Alchemist",
      "Ancient Apparition",
      "Antimage",
      "Arc Warden",
      "Axe",
      "Bane",
      "Batrider",
      "Beastmaster",
      "Bloodseeker",
      "Bounty Hunter",
      "Brewmaster",
      "Bristleback",
      "Broodmother",
      "Centaur Warrunner",
      "Chaos Knight",
      "Chen",
      "Clinkz",
      "Crystal Maiden",
      "Dark Seer",
      "Dark Willow",
      "Dawnbreaker",
      "Dazzle",
      "Death Prophet",
      "Disruptor",
      "Doom",
      "Dragon Knight",
      "Drow Danger",
      "Earth Spirit",
      "Earthshaker",
      "Elder Titan",
      "Ember Spirit",
      "Enchantress",
      "Enigma",
      "Faceless Void",
      "Nature's Prophet",
      "Grimstroke",
      "Gyrocopter",
      "Hoodwink",
      "Huskar",
      "Invoker",
      "Jakiro",
      "Juggernaut",
      "Keeper of the light",
      "Kunkka",
      "Legion Commander",
      "Leshrac",
      "Lich",
      "Lifestealer",
      "Lina",
      "Lion",
      "Lone Druid",
      "Luna",
      "Lycan",
      "Magnus",
      "Marci",
      "Mars",
      "Medusa",
      "Meepo",
      "Mirana",
      "Monkey King",
      "Morphling",
      "Muerta",
      "Naga Siren",
      "Necrophos",
      "Shadow Fiend",
      "Night Stalker",
      "Nyx",
      "Outworld Destroyer",
      "Ogre Magi",
      "Omniknight",
      "Oracle",
      "Pangolier",
      "Phantom Assassin",
      "Phantom Lancer",
      "Phoenix",
      "Primal Beast",
      "Puck",
      "Pudge",
      "Pugna",
      "Queen of pain",
      "Clockwerk",
      "Razor",
      "Riki",
      "Rubick",
      "Sand King",
      "Shadow Demon",
      "Shadow Shaman",
      "Timbersaw",
      "Silencer",
      "Wraith king",
      "Skywrath Mage",
      "Slardar",
      "Slark",
      "Snapfire",
      "Sniper",
      "Spectre",
      "Spirit Breaker",
      "Storm Spirit",
      "Sven",
      "Techies",
      "Templar Assassin",
      "Terrorblade",
      "Tidehunter",
      "Tinker",
      "Tiny",
      "Treant Protector",
      "Troll Warlord",
      "Tusk",
      "Undying",
      "Ursa",
      "Vengeful Spirit",
      "Venomancer",
      "Viper",
      "Visage",
      "Void Spirit",
      "Warlock",
      "Weaver",
      "Windranger",
      "Winter Wyvern",
      "IO",
      "Witch Doctor",
      "Zeus",
   ],
   image: [
      "./images/heroes/abaddon.jpg",
      "./images/heroes/abyssal_underlord.jpg",
      "./images/heroes/alchemist.jpg",
      "./images/heroes/ancient_apparition.jpg",
      "./images/heroes/antimage.jpg",
      "./images/heroes/arc_warden.jpg",
      "./images/heroes/axe.jpg",
      "./images/heroes/bane.jpg",
      "./images/heroes/batrider.jpg",
      "./images/heroes/beastmaster.jpg",
      "./images/heroes/bloodseeker.jpg",
      "./images/heroes/bounty_hunter.jpg",
      "./images/heroes/brewmaster.jpg",
      "./images/heroes/bristleback.jpg",
      "./images/heroes/broodmother.jpg",
      "./images/heroes/centaur.jpg",
      "./images/heroes/chaos_knight.jpg",
      "./images/heroes/chen.jpg",
      "./images/heroes/clinkz.jpg",
      "./images/heroes/crystal_maiden.jpg",
      "./images/heroes/dark_seer.jpg",
      "./images/heroes/dark_willow.jpg",
      "./images/heroes/dawnbreaker.jpg",
      "./images/heroes/dazzle.jpg",
      "./images/heroes/death_prophet.jpg",
      "./images/heroes/disruptor.jpg",
      "./images/heroes/doom_bringer.jpg",
      "./images/heroes/dragon_knight.jpg",
      "./images/heroes/drow_ranger.jpg",
      "./images/heroes/earth_spirit.jpg",
      "./images/heroes/earthshaker.jpg",
      "./images/heroes/elder_titan.jpg",
      "./images/heroes/ember_spirit.jpg",
      "./images/heroes/enchantress.jpg",
      "./images/heroes/enigma.jpg",
      "./images/heroes/faceless_void.jpg",
      "./images/heroes/furion.jpg",
      "./images/heroes/grimstroke.jpg",
      "./images/heroes/gyrocopter.jpg",
      "./images/heroes/hoodwink.jpg",
      "./images/heroes/huskar.jpg",
      "./images/heroes/invoker.jpg",
      "./images/heroes/jakiro.jpg",
      "./images/heroes/juggernaut.jpg",
      "./images/heroes/keeper_of_the_light.jpg",
      "./images/heroes/kunkka.jpg",
      "./images/heroes/legion_commander.jpg",
      "./images/heroes/leshrac.jpg",
      "./images/heroes/lich.jpg",
      "./images/heroes/life_stealer.jpg",
      "./images/heroes/lina.jpg",
      "./images/heroes/lion.jpg",
      "./images/heroes/lone_druid.jpg",
      "./images/heroes/luna.jpg",
      "./images/heroes/lycan.jpg",
      "./images/heroes/magnataur.jpg",
      "./images/heroes/marci.jpg",
      "./images/heroes/mars.jpg",
      "./images/heroes/medusa.jpg",
      "./images/heroes/meepo.jpg",
      "./images/heroes/mirana.jpg",
      "./images/heroes/monkey_king.jpg",
      "./images/heroes/morphling.jpg",
      "./images/heroes/muerta.jpg",
      "./images/heroes/naga_siren.jpg",
      "./images/heroes/necrolyte.jpg",
      "./images/heroes/nevermore.jpg",
      "./images/heroes/night_stalker.jpg",
      "./images/heroes/nyx_assassin.jpg",
      "./images/heroes/obsidian_destroyer.jpg",
      "./images/heroes/ogre_magi.jpg",
      "./images/heroes/omniknight.jpg",
      "./images/heroes/oracle.jpg",
      "./images/heroes/pangolier.jpg",
      "./images/heroes/phantom_assassin.jpg",
      "./images/heroes/phantom_lancer.jpg",
      "./images/heroes/phoenix.jpg",
      "./images/heroes/primal_beast.jpg",
      "./images/heroes/puck.jpg",
      "./images/heroes/pudge.jpg",
      "./images/heroes/pugna.jpg",
      "./images/heroes/queenofpain.jpg",
      "./images/heroes/rattletrap.jpg",
      "./images/heroes/razor.jpg",
      "./images/heroes/riki.jpg",
      "./images/heroes/rubick.jpg",
      "./images/heroes/sand_king.jpg",
      "./images/heroes/shadow_demon.jpg",
      "./images/heroes/shadow_shaman.jpg",
      "./images/heroes/shredder.jpg",
      "./images/heroes/silencer.jpg",
      "./images/heroes/skeleton_king.jpg",
      "./images/heroes/skywrath_mage.jpg",
      "./images/heroes/slardar.jpg",
      "./images/heroes/slark.jpg",
      "./images/heroes/snapfire.jpg",
      "./images/heroes/sniper.jpg",
      "./images/heroes/spectre.jpg",
      "./images/heroes/spirit_breaker.jpg",
      "./images/heroes/storm_spirit.jpg",
      "./images/heroes/sven.jpg",
      "./images/heroes/techies.jpg",
      "./images/heroes/templar_assassin.jpg",
      "./images/heroes/terrorblade.jpg",
      "./images/heroes/tidehunter.jpg",
      "./images/heroes/tinker.jpg",
      "./images/heroes/tiny.jpg",
      "./images/heroes/treant.jpg",
      "./images/heroes/troll_warlord.jpg",
      "./images/heroes/tusk.jpg",
      "./images/heroes/undying.jpg",
      "./images/heroes/ursa.jpg",
      "./images/heroes/vengefulspirit.jpg",
      "./images/heroes/venomancer.jpg",
      "./images/heroes/viper.jpg",
      "./images/heroes/visage.jpg",
      "./images/heroes/void_spirit.jpg",
      "./images/heroes/warlock.jpg",
      "./images/heroes/weaver.jpg",
      "./images/heroes/windrunner.jpg",
      "./images/heroes/winter_wyvern.jpg",
      "./images/heroes/wisp.jpg",
      "./images/heroes/witch_doctor.jpg",
      "./images/heroes/zuus.jpg",
   ],
   id: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
      76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
      94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
      110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
      125,
   ],
};

let heroesQuantity = 124; //Общее количество героев
let n = heroesQuantity;
let chanceDefault = (n / n ** 2) * 100;

const heroes = [
   {
      heroesId: 0,
      heroesName: "NotAHero",
      heroesImage: "NotAHero",
      heroesChance: 0,
   },
   {
      heroesId: 1,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 2,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 3,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 4,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 5,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 6,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 7,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 8,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 9,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 10,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 11,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 12,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 13,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 14,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 15,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 16,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 17,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 18,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 19,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 20,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 21,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 22,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 23,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 24,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 25,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 26,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 27,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 28,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 29,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 30,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 31,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 32,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 33,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 34,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 35,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 36,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 37,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 38,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 39,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 40,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 41,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 42,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 43,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 44,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 45,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 46,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 47,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 48,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 49,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 50,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 51,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 52,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 53,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 54,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 55,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 56,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 57,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 58,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 59,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 60,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 61,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 62,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 63,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 64,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 65,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 66,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 67,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 68,
      heroesName: "anc",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 69,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 70,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 71,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 72,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 73,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 74,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 75,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 76,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 77,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 78,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 79,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 80,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 81,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 82,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 83,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 84,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 85,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 86,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 87,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 88,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 89,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 90,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 91,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 92,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 93,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 94,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 95,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 96,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 97,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 98,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 99,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 100,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 101,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 102,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 103,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 104,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 105,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 106,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 107,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 108,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 109,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 110,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 111,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 112,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 113,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 114,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 115,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 116,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 117,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 118,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 119,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 120,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 121,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 122,
      heroesName: "Abaddon",
      heroesImage: "./images/heroes/abaddon.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 123,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
   {
      heroesId: 124,
      heroesName: "Underlord",
      heroesImage: "./images/heroes/abyssal_underlord.jpg",
      heroesChance: chanceDefault,
   },
];

let randId = 0;
let back = 0;
let heroButton = document.querySelector(".choose-button");
let heroImage = document.querySelector(".hero-image");
let lastHeroId = document.querySelector(".last-hero__id");
let lastHeroName = document.querySelector(".last-hero__name");
let rocketButton = document.querySelector(".rocket-button");
let rocketGo = document.querySelector(".rocket");
let lysina = document.querySelector(".lysina");

let summ = 0;
for (let i = 0; i <= heroes.length; i = i + 1) {
   summ = summ + heroes[i].heroesChance;
   console.log(summ);
}
